### ISSUE TITLE
Use Size when it should be used.

### ISSUE THREAD

**Issue by simonmika** [cogneco/ooc-kean#783]
Use `size` for translations not points. For example in `FloatEuclidTransform`. See https://github.com/cogneco/ooc-kean/pull/662 for details.

**Comment by simonmika** [comment]
Let us also change the properties of all size covers into `x` and `y`.

**Comment by bettinaselig** [comment]
Change `FloatSize2D` to a more intuitive name. @niklasborwell @sebastianbaginski @marcusnaslund @davidhesselbom

**Comment by bettinaselig** [comment]
Suggestions: `FloatVector2D`, `FloatDirection2D`

**Comment by simonmika** [comment]
What about `FloatDisplacement2D`?

**Comment by davidhesselbom** [comment]
Are we keeping `FloatSize2D`? A `FloatBox2D` consisting of a `FloatPoint2D` and a `FloatDisplacement2D` doesn't seem very intuitive.

**Comment by bettinaselig** [comment]
Just brain storming... `FloatTranslation2D`

**Comment by bettinaselig** [comment]
Can collect first and then make pick the best. please?

**Comment by marcusnaslund** [comment]
This has probably been brought up before but I'd like to point out that the `Point` covers have some properties that are generally associated (mathematically) to vectors, not points. So having a `FloatVector2D` and a `FloatPoint2D` would imply some consistency there which we don't have.

**Comment by davidhesselbom** [comment]
`FloatDimensions2D` should cover both size and translations.

**Comment by bettinaselig** [comment]
Ok. We can also discuss if `FloatPoint2D` can get a better name.

**Comment by niklasborwell** [comment]
If we're gonna make this change, I would prefer to clean up the things @marcusnaslund mentioned. Otherwise we're just exchanging a half-weird system for another.

**Comment by bettinaselig** [comment]
In computer graphics the terms are *location vector* and *direction vector*.

**Comment by bettinaselig** [comment]
Position: https://en.wikipedia.org/wiki/Position_%28vector%29
Direction: https://en.wikipedia.org/wiki/Direction_vector

**Comment by niklasborwell** [comment]
So I would suggest, remove all the things that are actually vector-related and move them into a general vector class, FloatVector2D. Keep the FloatPoints, but more specific. 
I think anybody would feel comfortable using a FloatVector2D, as it is a standard concept. A FloatDisplacement or FloatTranslation would just seem like special cases that would cause more confusion.

**Comment by marcusnaslund** [comment]
"Real" `Point` and `Vector` covers sound good to me, I am honestly quite confused by the division we have now.

**Comment by davidhesselbom** [comment]
I thought a point was a vector... :confused:

**Comment by bettinaselig** [comment]
Yes... well... it depends. In my world everything are tupels :-)

**Comment by bettinaselig** [comment]
Personally, I can live with `point` and `vector`. But I think to remember that @simonmika did not like this concept that much.

**Comment by tomasmahlberg** [comment]
If we are changing the properties in `size` to `x` and `y` and so on I will have to agree that `vector` would be the more intuitive and general naming. Then we would have one cover for positions (`point`) and one for displacements (`vector`) and they could also be used for more general cases, so my vote right now would also be on this set of covers. `translation`, `dimension`, `displacement` and so on all sound too specific as has been mentioned and are likely to cause some confusion, which I guess is what we're trying to avoid here.

**Comment by niklasborwell** [comment]
Talked with Simon today. He agreed with the idea of vectors + points, with the width, height, depth renamed to x, y and z. That means we are ready to fix this, but it is quite a big project. We should discuss who is going to to what. Volunteers welcome!

**Comment by marcusnaslund** [comment]
Haha, how fun for the person who has to review that PR! Oh wait..

**Comment by davidhesselbom** [comment]
Just wanted to say that I tried this, and it works, with no warnings and no errors from valgrind:
```ooc
Vector: cover {
    x, y: Int
    init: func@
}
Point: cover from Vector extends Vector {
    init: func@
    scalarProduct: func (other: This) -> Int { this x * other x + this y * other y }
}
Size: cover from Vector extends Vector {
    init: func@
    width: Int { get { this x } }
    height: Int { get { this y } }
    area ::= this width * this height
}

vector := Vector new()
vector x = 2
vector y = 3
size := vector as Size
size width toString() println() // prints 2, yay
size height toString() println() // prints 3, yay
size area toString() println() // prints 6, yay
point := size as Point
point scalarProduct(point) toString() println() // prints 13, yay
```
I haven't figured out how to *set* a `width` and `height`, unfortunately.

**Comment by davidhesselbom** [comment]
Fixed it:
```ooc
Vector: cover {
    x, y: Int
    init: func@
}
Point: cover from Vector extends Vector {
    init: func@
    scalarProduct: func (other: This) -> Int { this x * other x + this y * other y }
}
Size: cover from Vector extends Vector {
    init: func@
    width: extern (x) Int
    height: extern (y) Int
    area ::= this width * this height
}

vector := Vector new()
vector x = 2
vector y = 3
size := vector as Size
size width toString() println() // prints 2
size width = 4
size width toString() println() // prints 4
size height toString() println() // prints 3
size area toString() println() // prints 6
point := size as Point
point scalarProduct(point) toString() println() // prints 25, yay
```
So that means we can treat covers like objects with inheritance, and we can access `x` and `y` in `Vector` with the variables `width` and `height` in `Vector`s cast to `Size` as if the `Vector` were as `Size` all along, then back to `Vector` or `Point`, all without conversion constructors. Pretty neat, huh?

**Comment by niklasborwell** [comment]
Can you access `point x` and `point y`? And what about functions in `Vector`, are they accessible in `Point` and `Size`?

**Comment by davidhesselbom** [comment]
I added
```ooc
Vector: cover {
    x, y: Int
    init: func@
    foo: func -> Int { this x + this y }
}
```
and
```
    point x toString() println()
    point foo() toString() println()
``` 
and that works.

**Comment by davidhesselbom** [comment]
I don't know about you, but ooc just looks a whole lot better in my book.

**Comment by niklasborwell** [comment]
If it works properly, this would make this issue a whooole lot easier, and improve the code we have today a lot too. Let's hope we don't encounter any serious issues with it. I'm still a bit suspicious about the `width: extern (x) Int` part..

**Comment by davidhesselbom** [comment]
I'm not sure about the `extern` either, but that's how we use covers from external libraries already. Without it, we wouldn't be able to use the X11 window, for instance.

**Comment by bettinaselig** [comment]
That is awesome! 

So what about the naming problem? Since `Vector` is now taken, I guess we need to have a new discussion about `Size`. I still think we need a more intuitive name for that cover. 

I suggest `Direction` and some adjustments in `Box`:
- `Box` is defined by the point `leftTop` and a direction `direction`, which will span the box starting from `leftTop`.
- The properties `width` and `height` will be exchanged by
```
width ::= this direction x abs()
height ::= this direction y abs()
```

What do you think?

**Comment by davidhesselbom** [comment]
I don't like it. Why can't we keep `Size`? `Size` can "inherit" from `Vector` just like `Point` does, and we can add another cover for translations. `Size` can even "inherit" from that cover, or vice versa. I agree `Size` is a strange name for a cover that describes translations, but it's the only one that makes sense for describing a *size*, and I think a `Box` *should* have a size.

**Comment by bettinaselig** [comment]
If you do not like to store a negative direction in `Box`, we can also change the `init` function to check for that and recalculate `leftTop` and `direction` (to be positive).

This check should be included in any case, because currently a `Box` can be created with negative `Size`.

**Comment by davidhesselbom** [comment]
Ah, yes, we still have that problem...

**Comment by bettinaselig** [comment]
Yes, a `Box` should have a size... as *variable name*!

**Comment by bettinaselig** [comment]
We can agree on that David and I disagree :-)

**Comment by bettinaselig** [comment]
Ok. I can live with that we have `Point`, `Size` and `Direction` (or `Translation` or whatever) that inherit from `Vector`.

**Comment by niklasborwell** [comment]
I was thinking that we have a vector class that we can use directly. I don't see a reason to make it abstract. A `FloatVector2D` for translations in `EuclidTransform` makes sense. I don't think we have the need for a specific translation class, that would probably not have any additional properties compared to vector2D. This just means we can keep `size` with a vector backend for boxes and such.

**Comment by bettinaselig** [comment]
Would like to hear about @simonmika 's opinion about this.

**Comment by davidhesselbom** [comment]
We can't make `Vector` "abstract", and I'm not suggesting we don't use it for things. All I'm saying is that in some cases, it makes sense to call `Vector` something else, to even call its *fields*  something else (`x` and `y` -> `width` and `height`, in the case of `Size`), and give it functions it normally doesn't have, because those functions would bloat the `Vector` class. `cover from ... extends ...` allows us to do exactly that with no performance penalty, and I think we should take advantage of this.

**Comment by niklasborwell** [comment]
Good. I agree.

**Comment by bettinaselig** [comment]
Ok. You convinced me. I am also for this solution :-)

**Comment by davidhesselbom** [comment]
`FloatComplex` could also inherit from `FloatVector2D`, if we want.

**Comment by bettinaselig** [comment]
Sounds reasonable.

**Comment by tomasmahlberg** [comment]
+1 for this latest suggestion.

And this new-found feature looks awesome, so I had to try it out for a bit. It seems you have to declare getters and setters for variables in the base cover, otherwise things like `init: func@ (=x, =y)` in a derived cover gives this familiar error:
```
/home/tmahlberg/versioned/ooc/ooc-kean/cover_test.ooc: In function ‘cover_test__Point_init’:
/home/tmahlberg/versioned/ooc/ooc-kean/cover_test.ooc:17:37: error: lvalue required as left operand of assignment
   init: func@ (=x, =y)
                                     ^
/home/tmahlberg/versioned/ooc/ooc-kean/cover_test.ooc:17:37: error: lvalue required as left operand of assignment
   init: func@ (=x, =y)
                                     ^
C compiler failed on module cover_test from cover_test, bailing out
```

**Comment by bettinaselig** [comment]
Can someone make some issue, so we can start working on these changes?

**Comment by davidhesselbom** [comment]
@tomasmahlberg That's... a big problem. I reported it here: https://github.com/fasterthanlime/rock/issues/949

**Comment by davidhesselbom** [comment]
Still, it seems to be a fixable bug, and not a limitation in the language itself. I have no ETA, unfortunately, but perhaps we could lay low with this for a while until we know? I would prefer keeping our current, broken way of doing things over changing everything everywhere and then doing it all over again because the bug was fixed a few days or weeks later.

**Comment by bettinaselig** [comment]
Once more to the original issue: Transforms can only be applied to `Points`.

**Comment by simonmika** [comment]
I am still not convinced of the benefit of introducing yet another cover. Why would we need `Vector` and `Size`.

**Comment by davidhesselbom** [comment]
If you don't think we need it, okay, fine. `Point` can still "inherit" from `Vector`, though... well, if it weren't for the bug.

**Comment by niklasborwell** [comment]
I agree. We can have a property in box: `size: FloatVector2D`. I don't think there is a need for a specific `size` cover.

**Comment by niklasborwell** [comment]
Accidentally pressed close...sorry.

**Comment by bettinaselig** [comment]
Ok. My thoughts I have written here. I will exit this discussion now.

**Comment by simonmika** [comment]
This is what I think:

1. Rename size to vector.
1. Rename `width` and `height` to `x` and `y`.
1. Move all points, vectors, boxes, shells, etc into a `geometry` component.
1. No weird casts aka inheritance.
1. Kill `FloatPoint4D`. There is no such thing in our code.
1. And for complex numbers: Not everything with two values is a vector.

And in the context of the `geometry` component this is what is meant:

* Points are locations in space.
* Vectors are displacements in space.

**Comment by emilwestergren** [comment]
I need `FloatPoint4D` to be replaced with a 4 float vector.

**Comment by emilwestergren** [comment]
I'll take care of `FloatPoint4D` since it's my hack. https://github.com/cogneco/ooc-kean/issues/830

**Comment by simonmika** [comment]
This is how we will make the changes:
- [ ] Remove the need for FloatPoint4D. #830
- [ ] Rename `width` and `height` to `x` and `y`.
- [ ] Rename `Size` to `Vector`.
- [ ] Create `geometry` namespace.
- [ ] Ensure right use of `Vector` and `Point` everywhere.

@emilwestergren is doing the first one. Who wants to continue?

**Comment by marcusnaslund** [comment]
What's left to do in terms of "Ensure right use of Vector and Point everywhere."?

**Comment by niklasborwell** [comment]
Since it is hard to know when it is finished, this issue is probably not very useful anymore. If we find places where it should be changed, we can open new issues. I suggest closing this.

**Comment by marcusnaslund** [comment]
Agreed. An issue like "Do X wherever needed" doesn't quite fit our definition of a github issue.

**Comment by simonmika** [comment]
I was thinking about translation it `FloatEuclidTransform`. I nobody has any more ideas I will close tis now.
